### ISSUE TITLE
DateTimes sometimes corrupted

### ISSUE THREAD

**Issue by lylek** [v0d1ch/HExcel#1]
If I write an Excel document where each row has a timestamp written with writeDateTime, it will non-deterministically write the wrong time value, such as nan or some really large number. Here are three rows from a generated worksheet:

```
<row r="37" spans="1:3"><c r="A37" s="1"><v>43741.16666666666</v></c><c r="C37" t="s"><v>33</v></c></row>
<row r="38" spans="1:3"><c r="A38" s="1"><v>nan</v></c><c r="C38" t="s"><v>34</v></c></row>
<row r="39" spans="1:3"><c r="A39" s="1"><v>3.810139950172045e+227</v></c><c r="B39" t="s"><v>35</v></c></row>
```

The first row has a valid datetime (in the <v> tag). The other two do not. I dumped out the DateTime record from the Haskell program before it was written using writeDateTime, and it looked fine.

Running it multiple times produces errors on different rows, even though the code is completely deterministic.

So I can't tell whether this is a bug in HExcel, or in libxlswriter.

**Comment by v0d1ch** [comment]
Thanks for reporting this @lylek . Do you have some minimal code that is capable of reproducing this issue?

**Comment by v0d1ch** [comment]
@lylek Ok some debugging revealed that you need to make sure you set the format when writing `DateTime` values. For now until I release a fix for this just make sure you are setting the format correctly, something like :
```
  wb <- workbookNew "test.xlsx"
  let props = mkDocProperties
        { docPropertiesTitle   = "Test Workbook"
        , docPropertiesCompany = "HExcel"
        }
  workbookSetProperties wb props
  ws <- workbookAddWorksheet wb "First Sheet"
  df <- workbookAddFormat wb
  formatSetNumFormat df "mmm d yyyy hh:mm AM/PM"
  now <- getZonedTime
  writeDateTime ws (Just df) n 5 (zonedTimeToDateTime now)

```
Please re-open if you find further problems with this approach, closing this issue now. It will be implemented when this issue is resolved https://github.com/v0d1ch/HExcel/issues/2

**Comment by lylek** [comment]
Sorry I haven’t responded yet - have been very busy, but I will have time to get you a code sample next week. Thanks for your advice, but I have already been setting the format. It’s possible I’m doing something wrong with setting the format. I’ll try this out and get back to you.

**Comment by lylek** [comment]
> Thanks for reporting this @lylek . Do you have some minimal code that is capable of reproducing this issue?

Yes, @v0d1ch, here is some minimal code that reproduces the problem:

https://gist.github.com/lylek/2bcf2c33b7bdafc6e71e513a6254fd95

This script will generate an Excel file called `buggy-dates.xls`. It writes dates only to the first column, one in each row. It writes a date/time for each hour in November 2019.

But some of the datetimes (randomly) will be corrupted. Maybe two or three in the whole file.

**Comment by lylek** [comment]
> @lylek Ok some debugging revealed that you need to make sure you set the format when writing `DateTime` values. For now until I release a fix for this just make sure you are setting the format correctly, something like :
> 
> ```
>   wb <- workbookNew "test.xlsx"
>   let props = mkDocProperties
>         { docPropertiesTitle   = "Test Workbook"
>         , docPropertiesCompany = "HExcel"
>         }
>   workbookSetProperties wb props
>   ws <- workbookAddWorksheet wb "First Sheet"
>   df <- workbookAddFormat wb
>   formatSetNumFormat df "mmm d yyyy hh:mm AM/PM"
>   now <- getZonedTime
>   writeDateTime ws (Just df) n 5 (zonedTimeToDateTime now)
> ```
> 
> Please re-open if you find further problems with this approach, closing this issue now. It will be implemented when this issue is resolved #2

@v0d1ch, I posted a minimal bit of code reproducing the error. I don't have permission to re-open the issue, but perhaps you can?

**Comment by v0d1ch** [comment]
Hey @lylek , thanks for trying this out. I tried locally and could not reproduce it on my machine. I am on lts Ubuntu 18.04. What OS are you using? This might be platform/machine specific.

**Comment by lylek** [comment]
> Hey @lylek , thanks for trying this out. I tried locally and could not reproduce it on my machine. I am on lts Ubuntu 18.04. What OS are you using? This might be platform/machine specific.

I'm using libxlsxwriter 0.8.7 on macOS 10.14.6. It's possible the bug is in libxlsxwriter and I would have to write a C program to exercise it and find out.

**Comment by v0d1ch** [comment]
I am using this commit to test with https://github.com/jmcnamara/libxlsxwriter/tree/db9679832304852ec08263324745ba25773d7890
I pulled down the repo, installed it and I am providing stack with a lib folder using `--extra-lib-dirs` https://docs.haskellstack.org/en/stable/yaml_configuration/#extra-include-dirsextra-lib-dirs maybe that helps. Don't know how this feature is important for you.

**Comment by lylek** [comment]
> I am using this commit to test with https://github.com/jmcnamara/libxlsxwriter/tree/db9679832304852ec08263324745ba25773d7890
> I pulled down the repo, installed it and I am providing stack with a lib folder using `--extra-lib-dirs` https://docs.haskellstack.org/en/stable/yaml_configuration/#extra-include-dirsextra-lib-dirs maybe that helps. Don't know how this feature is important for you.

Thanks @v0d1ch! That newer version of libxlsxwriter fixes the problem for me. I don't see any discussion of a fix for that bug in the CHANGES file for libxlsxwriter. But either the older version had the bug or there was something wrong with the homebrew build of it. When I built it myself from the version you linked, and used that version to build my program, the problem goes away.
